### ISSUE TITLE
Versions des sources TEI ?

### ISSUE THREAD

**Issue by mingarao** [umr5037/skepsisTeiSources#4]
Je viens de monter sur Huma Num la version en cours de skepsis avec les facettes qui fonctionnent selon la v1 (1 sceptique / 1 notion)

J'ai dans un premier temps pris les sources TEI présentes sur github mais cela ne fonctionnait pas (visiblement, version sans les xml:id, etc.)

Donc j'ai pris les sources telles que sur AHN actuellement et cela fonctionne.

Il faut donc revoir quelle est la bonne version des sources et la commiter ici 

A bientôt !

**Comment by smarchand** [comment]
salut à tous, je choppe un bout de réseau à PAris :
il faut prendre les textes sur ahn, je n'ai pas mis à jour sur githutb, je
le ferai dès mon retour
merci ++

2015-07-09 17:55 GMT+02:00 mingarao <notifications@github.com>:

> Assigned #4 <https://github.com/umr5037/skepsisTeiSources/issues/4> to
> @smarchand <https://github.com/smarchand>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umr5037/skepsisTeiSources/issues/4#event-352035208>.
>



-- 
Stéphane
